spring:
  resources:
    cache:
      period: 0    
    static-locations: file:./client/,file:./client/ext/classic/locale/overrides/de/
  jpa:
    show-sql: true

server:
  port: 8080
  compression:
    enabled: false

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.apache: INFO
    liquibase: INFO
    ch: INFO