info:
  app.name: "@project.name@"
  app.description: "@project.description@"
  app.version: "@project.version@"
  build.artifact: "@project.artifactId@"
  build.time: "@build.timestamp@"

app:
  url: http://localhost:8080
  rememberme-cookie-key: starter
  rememberme-cookie-valid-in-days: 31
  default-email-sender: no-reply@starter.com
  login-lock-attempts: 10
  login-lock-minutes: 30

spring:
  jackson:
    serialization:
      write-date-timestamps-as-nanoseconds: false
  
  resources:
    cache:
      period: 31556926
  
  mvc:
    favicon:
      enabled: false

  mail:
    host: localhost    
  
  datasource:
        url: jdbc:h2:./db/test
        username: sa
        password: sa
        #driver-class-name: com.mysql.cj.jdbc.Driver
        #url: jdbc:mysql://localhost/starter6?nullNamePatternMatchesAll=true&useSSL=false
        #username: root
        #password: root        
        tomcat:
          max-active: 100
          max-idle: 10
          min-idle: 4
          initial-size: 4
          validation-query: select 1
          test-on-borrow: true
          test-on-return: false
          test-while-idle: true
          time-between-eviction-runs-millis: 120000
          min-evictable-idle-time-millis: 60000
          max-wait: 10000
          remove-abandoned: true
          validation-interval: 120000
          remove-abandoned-timeout: 600
        jmx-enabled: false

  async:
    core-pool-size: 2
    max-pool-size: 20
    queue-capacity: 200
    thread-name-prefix: starter-async-executor

  jpa:
    hibernate:
      ddl-auto: validate

  main:
    banner-mode: log       
      

  liquibase:
    change-log: classpath:/db/changelog.xml

server:
  port: 80
  servlet:
    session:
      timeout: 480
#  compression:
#     enabled: true
#     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,image/svg+xml,application/x-font-ttf,application/x-font-truetype,application/x-font-opentype,application/vnd.ms-fontobject,application/font-sfnt     
  use-forward-headers: true

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    org.apache: WARN
    liquibase: WARN
    ch: WARN
  file: ./app.log

management:
  server:
    add-application-context-header: false
  endpoint:
    metrics:
      enabled: false